# -*- coding: utf-8 -*-
"""chile

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qAW3q6fMvLo3rHSobls9aVHsVb1X17mj
"""

# =========================================================
# PROYECTO ESTADÍSTICO OECD - CHILE
# GOOGLE COLAB COMPLETO
# =========================================================

# =========================================================
# LIBRERÍAS
# =========================================================

import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from io import StringIO
from scipy import stats
from scipy.stats import binom, poisson, hypergeom, norm
from matplotlib_venn import venn2
from math import factorial, comb

# =========================================================
# API OECD - CHILE
# =========================================================

url = "https://sdmx.oecd.org/sti-public/rest/data/OECD.STI.PIE,DSD_BTIGE@DF_BTIGE,1.0/A.CHL.X.TOTAL..W.?startPeriod=2015&dimensionAtObservation=AllDimensions&format=csvfilewithlabels"

response = requests.get(url)

df = pd.read_csv(StringIO(response.text))

# =========================================================
# LIMPIEZA DE DATOS
# =========================================================

df = df[['TIME_PERIOD', 'OBS_VALUE']]

df['TIME_PERIOD'] = pd.to_numeric(df['TIME_PERIOD'], errors='coerce')
df['OBS_VALUE'] = pd.to_numeric(df['OBS_VALUE'], errors='coerce')

df = df.dropna()

# =========================================================
# AGRUPAR POR AÑO
# =========================================================

df_grouped = df.groupby('TIME_PERIOD')['OBS_VALUE'].sum().reset_index()

años = df_grouped['TIME_PERIOD']
valores = df_grouped['OBS_VALUE']

# =========================================================
# DATOS UTILIZADOS
# =========================================================

print("\n========================")
print("DATOS DE CHILE UTILIZADOS")
print("========================")

print(df_grouped)

# =========================================================
# DATOS AGRUPADOS
# =========================================================

print("\n========================")
print("DATOS AGRUPADOS")
print("========================")

intervalos = pd.cut(valores, bins=4)

frecuencias = intervalos.value_counts()

print("\nFrecuencias agrupadas:")
print(frecuencias)

moda_agrupada = frecuencias.idxmax()

media_agrupada = valores.mean()

mediana_agrupada = valores.median()

# =========================================================
# GRÁFICA 1
# =========================================================

plt.figure(figsize=(10,6))

plt.plot(años, valores, marker='o')

plt.title("Comercio Total de Chile")

plt.xlabel("Año")

plt.ylabel("OBS_VALUE")

plt.grid(True)

plt.savefig("grafica1.png", dpi=300, bbox_inches='tight')

plt.show()

# =========================================================
# DATOS NO AGRUPADOS
# =========================================================

print("\n========================")
print("DATOS NO AGRUPADOS")
print("========================")

# =========================================================
# 2.1 MODA
# =========================================================

print("\n========================")
print("2.1 MODA")
print("========================")

moda = stats.mode(valores, keepdims=True)

print("\nProblema:")
print("Encontrar el valor comercial que más se repite.")

print("\nFórmula:")
print("Moda = valor con mayor frecuencia")

print("\nValores utilizados:")
print(list(valores))

print("\nResultado:")
print(moda.mode[0])

print("\nInterpretación:")
print("Uno de los valores comerciales más frecuentes de Chile fue aproximadamente", moda.mode[0])

# =========================================================
# 2.2 MEDIANA
# =========================================================

print("\n========================")
print("2.2 MEDIANA")
print("========================")

ordenados = sorted(valores)

mediana = np.median(ordenados)

print("\nProblema:")
print("Calcular el valor central del comercio chileno.")

print("\nDatos ordenados:")
print(ordenados)

print("\nFórmula:")
print("Mediana = (dato central 1 + dato central 2) / 2")

print("\nSustitución:")
print(f"Mediana = ({ordenados[4]} + {ordenados[5]}) / 2")

print("\nResultado:")
print(mediana)

print("\nInterpretación:")
print("La mitad de los años tuvieron un comercio menor y la otra mitad mayor.")

# =========================================================
# 2.3 MEDIA
# =========================================================

print("\n========================")
print("2.3 MEDIA")
print("========================")

suma_valores = valores.sum()

cantidad = len(valores)

media = suma_valores / cantidad

print("\nProblema:")
print("Calcular el promedio del comercio total de Chile.")

print("\nValores utilizados:")
print(list(valores))

print("\nFórmula:")
print("Media = suma de valores / cantidad")

print("\nSuma total:")
print(suma_valores)

print("\nCantidad:")
print(cantidad)

print("\nSustitución:")
print(f"Media = {suma_valores} / {cantidad}")

print("\nResultado:")
print(media)

print("\nInterpretación:")
print("El comercio promedio anual de Chile fue aproximadamente", media)

# =========================================================
# 2.4 MODA AGRUPADA
# =========================================================

print("\n========================")
print("2.4 MODA AGRUPADA")
print("========================")

print("\nProblema:")
print("Encontrar el intervalo con mayor frecuencia.")

print("\nResultado:")
print(moda_agrupada)

# =========================================================
# 2.5 MEDIANA AGRUPADA
# =========================================================

print("\n========================")
print("2.5 MEDIANA AGRUPADA")
print("========================")

print("\nResultado:")
print(mediana_agrupada)

# =========================================================
# 2.6 MEDIA AGRUPADA
# =========================================================

print("\n========================")
print("2.6 MEDIA AGRUPADA")
print("========================")

print("\nResultado:")
print(media_agrupada)

# =========================================================
# GRÁFICA 2
# =========================================================

plt.figure(figsize=(10,6))

plt.plot(años, valores, marker='o')

plt.axhline(media, linestyle='--')

plt.title("Media del Comercio de Chile")

plt.xlabel("Año")

plt.ylabel("OBS_VALUE")

plt.grid(True)

plt.savefig("grafica2.png", dpi=300, bbox_inches='tight')

plt.show()

# =========================================================
# 3.1 RANGO
# =========================================================

print("\n========================")
print("3.1 RANGO")
print("========================")

maximo = np.max(valores)

minimo = np.min(valores)

rango = maximo - minimo

print("\nProblema:")
print("Calcular la diferencia entre el mayor y menor valor.")

print("\nFórmula:")
print("Rango = máximo - mínimo")

print("\nValor máximo:")
print(maximo)

print("\nValor mínimo:")
print(minimo)

print("\nSustitución:")
print(f"Rango = {maximo} - {minimo}")

print("\nResultado:")
print(rango)

print("\nInterpretación:")
print("Existe una diferencia importante entre los años de mayor y menor comercio.")

# =========================================================
# 3.2 RANGO INTERCUARTÍLICO
# =========================================================

print("\n========================")
print("3.2 RANGO INTERCUARTÍLICO")
print("========================")

Q1 = valores.quantile(25/100)

Q3 = valores.quantile(75/100)

RIQ = Q3 - Q1

print("\nProblema:")
print("Calcular el intervalo donde se concentra la mayoría de datos.")

print("\n¿Por qué 25/100?")
print("Porque Q1 representa el 25% de los datos.")

print("\n¿Por qué 75/100?")
print("Porque Q3 representa el 75% de los datos.")

print("\nQ1:")
print(Q1)

print("\nQ3:")
print(Q3)

print("\nFórmula:")
print("RIQ = Q3 - Q1")

print("\nSustitución:")
print(f"RIQ = {Q3} - {Q1}")

print("\nResultado:")
print(RIQ)

print("\nInterpretación:")
print("La mayoría de los datos comerciales de Chile se encuentran dentro de este intervalo.")

# =========================================================
# GRÁFICA 3
# =========================================================

plt.figure(figsize=(8,6))

plt.boxplot(valores)

plt.title("Boxplot Comercio de Chile")

plt.grid(True)

plt.savefig("grafica3.png", dpi=300, bbox_inches='tight')

plt.show()

# =========================================================
# 3.3 VARIANZA
# =========================================================

print("\n========================")
print("3.3 VARIANZA")
print("========================")

varianza = np.var(valores, ddof=1)

print("\nProblema:")
print("Medir la dispersión respecto a la media.")

print("\nFórmula:")
print("Varianza = Σ(x-media)^2 / (n-1)")

print("\nResultado:")
print(varianza)

# =========================================================
# 3.4 DESVIACIÓN ESTÁNDAR
# =========================================================

print("\n========================")
print("3.4 DESVIACIÓN ESTÁNDAR")
print("========================")

desviacion_estandar = np.std(valores, ddof=1)

print("\nProblema:")
print("Calcular cuánto se alejan los datos respecto al promedio.")

print("\nFórmula:")
print("Desviación estándar = raíz(varianza)")

print("\nResultado:")
print(desviacion_estandar)

# =========================================================
# 3.5 DESVIACIÓN MEDIA
# =========================================================

print("\n========================")
print("3.5 DESVIACIÓN MEDIA")
print("========================")

desviacion_media = np.mean(np.abs(valores - media))

print("\nProblema:")
print("Calcular el alejamiento promedio absoluto.")

print("\nFórmula:")
print("DM = promedio de |x-media|")

print("\nResultado:")
print(desviacion_media)

# =========================================================
# CRECIMIENTO
# =========================================================

df_grouped['Crecimiento'] = df_grouped['OBS_VALUE'].pct_change()

df_grouped['Exito'] = np.where(df_grouped['Crecimiento'] > 0, 1, 0)

A = set(df_grouped[df_grouped['Exito']==1]['TIME_PERIOD'])

B = set(df_grouped[df_grouped['OBS_VALUE']>media]['TIME_PERIOD'])

# =========================================================
# 4.1 DIAGRAMA DE VENN
# =========================================================

print("\n========================")
print("4.1 DIAGRAMA DE VENN")
print("========================")

print("\nConjunto A:")
print(A)

print("\nConjunto B:")
print(B)

plt.figure(figsize=(7,7))

venn2([A,B],
      set_labels=('Crecimiento','Sobre Media'))

plt.title("Diagrama de Venn Chile")

plt.savefig("grafica4.png", dpi=300, bbox_inches='tight')

plt.show()

# =========================================================
# 4.2 CONTEO
# =========================================================

print("\n========================")
print("4.2 CONTEO")
print("========================")

conteo = len(valores)

print("\nResultado:")
print(conteo)

# =========================================================
# 4.3 COMBINACIÓN
# =========================================================

print("\n========================")
print("4.3 COMBINACIÓN")
print("========================")

r = len(A)

combinacion = comb(conteo,r)

print("\nFórmula:")
print("C(n,r)= n! / r!(n-r)!")

print("\nValores:")
print("n =", conteo)
print("r =", r)

print("\nResultado:")
print(combinacion)

# =========================================================
# 4.4 PERMUTACIÓN
# =========================================================

print("\n========================")
print("4.4 PERMUTACIÓN")
print("========================")

permutacion = factorial(r)

print("\nFórmula:")
print("n!")

print("\nResultado:")
print(permutacion)

# =========================================================
# 4.5 PROBABILIDAD CONDICIONAL
# =========================================================

print("\n========================")
print("4.5 PROBABILIDAD CONDICIONAL")
print("========================")

P_B = len(B)/conteo

inter = len(A.intersection(B))

P_AyB = inter/conteo

P_A_dado_B = P_AyB/P_B

print("\nFórmula:")
print("P(A|B)=P(A∩B)/P(B)")

print("\nResultado:")
print(P_A_dado_B)

# =========================================================
# 4.6 BAYES
# =========================================================

print("\n========================")
print("4.6 BAYES")
print("========================")

P_A = len(A)/conteo

P_B_dado_A = P_AyB/P_A

bayes = (P_B_dado_A*P_A)/P_B

print("\nResultado:")
print(bayes)

# =========================================================
# 5.1 DISTRIBUCIÓN BINOMIAL
# =========================================================

print("\n========================")
print("5.1 DISTRIBUCIÓN BINOMIAL")
print("========================")

n = conteo

k = r

p = k/n

binomial = comb(n,k)*(p**k)*((1-p)**(n-k))

print("\n¿Por qué p=k/n?")
print("Porque la probabilidad se obtiene de éxitos / total de datos.")

print("\nn:")
print(n)

print("\nk:")
print(k)

print("\np:")
print(p)

print("\nResultado:")
print(binomial)

# =========================================================
# GRÁFICA 5
# =========================================================

x_bin = np.arange(0,n+1)

y_bin = [comb(n,i)*(p**i)*((1-p)**(n-i)) for i in x_bin]

plt.figure(figsize=(10,6))

plt.bar(x_bin,y_bin)

plt.title("Distribución Binomial Chile")

plt.xlabel("Número de éxitos")

plt.ylabel("Probabilidad")

plt.grid(True)

plt.savefig("grafica5.png", dpi=300, bbox_inches='tight')

plt.show()

# =========================================================
# 5.2 DISTRIBUCIÓN POISSON
# =========================================================

print("\n========================")
print("5.2 DISTRIBUCIÓN POISSON")
print("========================")

eventos = r

lam = eventos/conteo

x = eventos

poisson_resultado = ((lam**x)*np.exp(-lam))/factorial(x)

print("\n¿Por qué lambda = eventos/conteo?")
print("Porque representa el promedio de eventos.")

print("\nLambda:")
print(lam)

print("\nResultado:")
print(poisson_resultado)

# =========================================================
# 5.3 HIPERGEOMÉTRICA
# =========================================================

print("\n========================")
print("5.3 HIPERGEOMÉTRICA")
print("========================")

N = conteo

K = r

n_hiper = round(N/2)

x_hiper = round(K/2)

hipergeometrica = (comb(K,x_hiper)*comb(N-K,n_hiper-x_hiper))/comb(N,n_hiper)

print("\nResultado:")
print(hipergeometrica)

# =========================================================
# 6.1 DISTRIBUCIÓN NORMAL
# =========================================================

print("\n========================")
print("6.1 DISTRIBUCIÓN NORMAL")
print("========================")

print("\nMedia:")
print(media)

print("\nDesviación estándar:")
print(desviacion_estandar)

# =========================================================
# 6.2 NORMAL ESTÁNDAR
# =========================================================

print("\n========================")
print("6.2 NORMAL ESTÁNDAR")
print("========================")

z_scores = (valores-media)/desviacion_estandar

print("\nFórmula:")
print("Z=(x-media)/desviación estándar")

print("\nResultados:")
print(z_scores)

# =========================================================
# 7.1 ÍNDICE PAASCHE
# =========================================================

print("\n========================")
print("7.1 ÍNDICE PAASCHE")
print("========================")

precio_actual = valores.iloc[-1]

precio_base = valores.iloc[0]

paasche = precio_actual/precio_base

print("\nResultado:")
print(paasche)

# =========================================================
# 7.2 ÍNDICE LASPEYRES
# =========================================================

print("\n========================")
print("7.2 ÍNDICE LASPEYRES")
print("========================")

laspeyres = media/precio_base

print("\nResultado:")
print(laspeyres)

# =========================================================
# 7.3 ÍNDICE FISHER
# =========================================================

print("\n========================")
print("7.3 ÍNDICE FISHER")
print("========================")

fisher = np.sqrt(paasche*laspeyres)

print("\nFórmula:")
print("Fisher = raíz(Paasche × Laspeyres)")

print("\nResultado:")
print(fisher)

# =========================================================
# DESCARGAR GRÁFICAS EN COLAB
# =========================================================

from google.colab import files

files.download("grafica1.png")
files.download("grafica2.png")
files.download("grafica3.png")
files.download("grafica4.png")
files.download("grafica5.png")

print("\nTodas las gráficas fueron generadas correctamente.")